-- Define your visual elements here
-- For examples, and a complete list on the possible elements and their 
-- properties, go to https://github.com/fisadev/conky-draw/
-- (and be sure to use the lastest version)


elements = {
    {
        kind = 'bar_graph',
        conky_value = 'cpu cpu0 /',
        from = { x = 120, y = 25 },
        to = { x = 230, y = 25 },
        background_thickness = 6,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 4,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = false,
        -- number_graduation = 26,
        -- space_between_graduation = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'memperc',
        from = { x = 426, y = 25 },
        to = { x = 536, y = 25 },
        background_thickness = 6,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 4,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = false,
        -- number_graduation = 26,
        -- space_between_graduation = 2,
    },
    {
        kind = 'bar_graph',
        -- AMD v
        conky_value = "exec cat /sys/class/drm/card0/device/gpu_busy_percent",
        -- NVIDIA v
        -- conky_value = "nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu | awk -F'[^0-9]*' '{ print $1 }'",
        from = { x = 743, y = 25 },
        to = { x = 853, y = 25 },
        background_thickness = 6,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 4,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = false,
        -- number_graduation = 26,
        -- space_between_graduation = 2,
        critical_threshold = 85,
    },
    {
        kind = 'bar_graph',
        conky_value = 'exec ${RICE_COOKER_DIST}/qemu-windows/scripts/vfio-load.sh',
        from = { x = 1060, y = 25 },
        to = { x = 1170, y = 25 },
        background_thickness = 6,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 4,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = false,
        -- number_graduation = 26,
        -- space_between_graduation = 2,
        critical_threshold = 85,
    },
    {
        kind = 'bar_graph',
        conky_value = 'fs_used_perc /',
        from = { x = 1438, y = 25 },
        to = { x = 1548, y = 25 },
        background_thickness = 6,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 4,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = false,
        -- number_graduation = 26,
        -- space_between_graduation = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'fs_used_perc /home/',
        from = { x = 1850, y = 25 },
        to = { x = 1960, y = 25 },
        background_thickness = 6,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 4,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = false,
        -- number_graduation = 26,
        -- space_between_graduation = 2,
    },
}
