-- Define your visual elements here
-- For examples, and a complete list on the possible elements and their 
-- properties, go to https://github.com/fisadev/conky-draw/
-- (and be sure to use the lastest version)


elements = {
    {
        kind = 'bar_graph',
        conky_value = "exec grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print int(usage)}'",
        from = { x = 80, y = 25 },
        to = { x = 190, y = 25 },
        background_thickness = 15,
        background_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        background_alpha = 0.5,
        bar_color = ${THEME_BACKGROUND_LIGHT_HEXDEC},
        bar_thickness = 15,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        graduated = false,
        -- number_graduation = 26,
        -- space_between_graduation = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'memperc',
        from = { x = 386, y = 25 },
        to = { x = 496, y = 25 },
        background_thickness = 15,
        background_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        background_alpha = 0.5,
        bar_color = ${THEME_BACKGROUND_LIGHT_HEXDEC},
        bar_thickness = 15,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        graduated = false,
        -- number_graduation = 26,
        -- space_between_graduation = 2,
    },
    {
        kind = 'bar_graph',
        -- AMD v
        --conky_value = "exec cat /sys/class/drm/card0/device/gpu_busy_percent",
        -- NVIDIA v
        conky_value = "exec nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu | awk -F'[^0-9]*' '{ print $1 }'",
        from = { x = 700, y = 25 },
        to = { x = 810, y = 25 },
        background_thickness = 15,
        background_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        background_alpha = 0.5,
        bar_color = ${THEME_BACKGROUND_LIGHT_HEXDEC},
        bar_thickness = 15,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        graduated = false,
        -- number_graduation = 26,
        -- space_between_graduation = 2,
        critical_threshold = 95,
    },
    --{
    --    kind = 'bar_graph',
    --    conky_value = 'exec ${RICE_COOKER_DIST}/qemu-windows/vfio-load.sh',
    --    from = { x = 1020, y = 25 },
    --    to = { x = 1130, y = 25 },
    --    background_thickness = 15,
    --    background_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
    --    background_alpha = 0.5,
    --    bar_color = ${THEME_BACKGROUND_LIGHT_HEXDEC},
    --    bar_thickness = 15,
    --    bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
    --    background_color_critical = ${THEME_FOREGROUND_LIGHT_HEXDEC},
    --    graduated = false,
    --    -- number_graduation = 26,
    --    -- space_between_graduation = 2,
    --    critical_threshold = 85,
    --},
    {
        kind = 'bar_graph',
        conky_value = 'fs_used_perc /',
        from = { x = 1105, y = 25 },
        to = { x = 1215, y = 25 },
        background_thickness = 15,
        background_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        background_alpha = 0.5,
        bar_color = ${THEME_BACKGROUND_LIGHT_HEXDEC},
        bar_thickness = 15,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        graduated = false,
        -- number_graduation = 26,
        -- space_between_graduation = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'fs_used_perc /home/',
        from = { x = 1510, y = 25 },
        to = { x = 1620, y = 25 },
        background_thickness = 15,
        background_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        background_alpha = 0.5,
        bar_color = ${THEME_BACKGROUND_LIGHT_HEXDEC},
        bar_thickness = 15,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        graduated = false,
        -- number_graduation = 26,
        -- space_between_graduation = 2,
    },
}
