-- Define your visual elements here
-- For examples, and a complete list on the possible elements and their 
-- properties, go to https://github.com/fisadev/conky-draw/
-- (and be sure to use the lastest version)


elements = {
    {
        kind = 'bar_graph',
        conky_value = 'cpu cpu0 /',
        from = { x = 150, y = 25 },
        to = { x = 450, y = 25 },
        background_thickness = 24,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 20,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = true,
        number_graduation = 26,
        space_between_graduation = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'memperc',
        from = { x = 726, y = 25 },
        to = { x = 1026, y = 25 },
        background_thickness = 24,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 20,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = true,
        number_graduation = 26,
        space_between_graduation = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = "exec cat /sys/class/drm/card0/device/gpu_busy_percent",
        from = { x = 1320, y = 25 },
        to = { x = 1620, y = 25 },
        background_thickness = 24,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 20,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = true,
        number_graduation = 26,
        space_between_graduation = 2,
        critical_threshold = 85,
    },
    {
        kind = 'bar_graph',
        conky_value = 'exec ${RICE_COOKER_DIST}/qemu-windows/scripts/vfio-load.sh',
        from = { x = 1910, y = 25 },
        to = { x = 2210, y = 25 },
        background_thickness = 24,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 20,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = true,
        number_graduation = 26,
        space_between_graduation = 2,
        critical_threshold = 85,
    },
    {
        kind = 'bar_graph',
        conky_value = 'fs_used_perc /',
        from = { x = 2565, y = 25 },
        to = { x = 2865, y = 25 },
        background_thickness = 24,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 20,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = true,
        number_graduation = 26,
        space_between_graduation = 2,
    },
    {
        kind = 'bar_graph',
        conky_value = 'fs_used_perc /home/',
        from = { x = 3260, y = 25 },
        to = { x = 3560, y = 25 },
        background_thickness = 24,
        background_color = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        background_alpha = 1,
        bar_color = ${THEME_FOREGROUND_LIGHT_HEXDEC},
        bar_thickness = 20,
        bar_color_critical = ${THEME_COLOUR_BRIGHT_RED_HEXDEC},
        background_color_critical = ${THEME_BACKGROUND_LIGHTER_HEXDEC},
        graduated = true,
        number_graduation = 26,
        space_between_graduation = 2,
    },
}
