#!/usr/bin/env bash

# docker build -t globalnode < ./Dockerfiles/npm

docker run --rm --interactive --tty \
    --user 'node' \
    --volume $PWD:/app \
    --workdir /app \
    globalnode:latest \
    npm $@
