#!/usr/bin/env bash

DOCKER_SERVICE=$(docker ps --filter "name=docker_app-php_1" --quiet)
NEUTRON=$(neutron-project $PWD)


if [ ! -z "${DOCKER_SERVICE}" ] && [ -f "${NEUTRON}/docker/docker-compose.yml" ]; then
    docker run --rm --interactive --tty \
        --user "$(id -u):$(id -g)" \
        --volume $PWD:/usr/share/nginx/html \
        --volume $NEUTRON/current:/packages \
        --workdir /usr/share/nginx/html \
        --network docker \
        docker_app-php \
        php -d memory_limit=-1 $@
else
    docker run --rm --interactive --tty \
        --user "$(id -u):$(id -g)" \
        --volume $PWD:/usr/share/nginx/html \
        --workdir /usr/share/nginx/html \
        php \
        php -d memory_limit=-1 $@
fi
